title: Matthew Miner and Samantha Lewis's Wedding Website
author:
  name: Matthew Miner
  email: mminer237@gmail.com
  site: https://matthewminer.name
themeColor: "#052f57"
manFirstName: Matthew
manLastName: Miner
womanFirstName: Samantha
womanLastName: Lewis
date: 2021-06-12
rsvpDeadline: 2021-05-08
location: Champaign, IL

plugins:
  - jekyll-responsive-image
  - jekyll-sitemap
  - generator

googleFonts:
  - Cormorant+Garamond:300,400,700
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "_pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    permalink: /:path

sass:
  style: compressed

responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 4096
    - width: 1920
    - width: 1080
    - width: 720
    - width: 640
    - width: 540
    - width: 480
    - width: 240
    - width: 150
  auto_rotate: true

include:
  - _redirects